# Generated by Django 2.2.1 on 2019-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20190604_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='added_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='date_modified',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
