# Generated by Django 2.2.1 on 2019-06-11 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0008_auto_20190610_0556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IP', 'In Processing'), ('OH', 'On Hold'), ('C', 'Cancelled'), ('OFD', 'Out For Delivery'), ('R', 'Returned'), ('D', 'Delivered')], default='IP', max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IP', 'In Processing'), ('OH', 'On Hold'), ('C', 'Cancelled'), ('OFD', 'Out For Delivery'), ('R', 'Returned'), ('D', 'Delivered')], default='IP', max_length=20)),
                ('total_amount', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('coupons', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Card', 'Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet')], default='COD', max_length=20)),
                ('shipping_address', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrderDetail')),
            ],
        ),
    ]
