# Generated by Django 2.2.1 on 2019-06-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0014_auto_20190611_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IP', 'In Processing'), ('OH', 'On Hold'), ('C', 'Cancelled'), ('OFD', 'Out For Delivery'), ('R', 'Returned'), ('D', 'Delivered')], default='IP', max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('coupons', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Card', 'Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet')], default='COD', max_length=20)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=256, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IP', 'In Processing'), ('OH', 'On Hold'), ('C', 'Cancelled'), ('OFD', 'Out For Delivery'), ('R', 'Returned'), ('D', 'Delivered')], default='IP', max_length=20)),
                ('order_price', models.IntegerField(null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
    ]
