# Generated by Django 2.2.1 on 2019-06-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_price',
        ),
    ]
