# Generated by Django 2.2.1 on 2019-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190612_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=20, unique=True),
        ),
    ]
