# Generated by Django 2.2.1 on 2019-06-13 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_auto_20190612_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'label')},
        ),
    ]
